### ISSUE TITLE
Receive payments address gap issue

### ISSUE THREAD

**Issue by anver** [blockchain/receive-payments-demos#35]
Below is my current setup :

1. New addresses are generated using the wallet api and users pay to those addresses. I'm using a legacy wallet, so the callback url is already setup inside the notifications settings area in the legacy wallet.

2. I receive the payments into the generated address from users and affiliates gets paid out using the wallet api. I don't have any issue so far but now I need to create an other setup like the same but unfortunately the legacy wallet cannot be created anymore which leaves me with only one option, that is to create the new HD blockchain wallet.

So my question is If I'm using receive payments api with the xpub key from the new hd wallet then there will be thousands of addresses created and there will be many address gaps which leaves the funds being unusable or not shows up inside the new wallet.
 
1. Each address I generate will be generated with a different callback urls based on the different order id's so that I can trace and create memberships based on the order data which was generated and saved for future use if a user actually pays for example : order_id : 1234 points to Order data : { username : xyz, duration: 2 months, membership_type: platinum } etc ..... so callback urls change for each users who is going to generate those new addresses which puts many address gaps. I know I can reuse the already generated address but is there is a way to change the callback_url of the already generated address ?

2. If there is no option to change the callback_url of an existing address which received no funds yet then is there a way to retrieve the funds that sits after the gap like programmatically accessing those funds etc ...

3. I know I can pass a gap limit parameter but still thousands of users means there will be atleast one gap created when users browse the site. I checked the gap checker by using "Check address gap" and currently it shows me 98 gaps.

Please let me know a solution so that I can move forward.

**Comment by HiddenMotives** [comment]
Your setup is not ideal, you should not be generating a unique callback URL for each address, instead you should have a single callback URL and pass custom parameters through it such as you mentioned above username, duration, membership_type.

**Comment by anver** [comment]
@HiddenMotives the url is the same but the order id will be different since each order is different and yes the order_id is a query variable of that url, so I'm using the same callback url with custom parameter as order_id. Don't worry I've implemented my own ipn notification system.

**Comment by batman567** [comment]
I have the same problem as anver - and i'm surprised more people don't either, unless i grossly misunderstand the problem.

I could eaily generate 20 addresses, each with unique callback (unique because of e.g. custom parameter transactionId). However i cannot generate more because of "gap", and don't really want to override and go beyond that.

I'm happy to re-use addresses, but i don't see how each of the subsequent payment notifications will link to their corresponding transaction - since a callback url with transactionId is setup the first time only when an address is generated.

Put another way - if one address (with one callback url) is re-used 5 times, how do i know which one of the 5 users made the payment?

**Comment by PhamDiesel** [comment]
mission to build a more open, accessible, and fair financial future, one piece of software at a time.
